# Docker composer helper to launch Ollama local server with GPU support
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    command: ["serve"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  web:
    build: .
    container_name: epub_translator_web
    ports:
      - "7860:7860"
    volumes:
      - ./:/app:rw
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped